/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#586064",
        "secondary-dim": "#3d5762",
        "on-primary-container": "#425366",
        "secondary-fixed-dim": "#bdd9e6",
        "on-secondary-fixed": "#29434e",
        "on-primary": "#f5f8ff",
        "secondary-fixed": "#cbe7f5",
        background: "#f8f9fa",
        "on-background": "#2b3437",
        "outline-variant": "#abb3b7",
        "on-tertiary-fixed-variant": "#556665",
        "on-primary-fixed": "#304153",
        "on-error-container": "#752121",
        "error-container": "#fe8983",
        secondary: "#49636f",
        "on-error": "#fff7f6",
        "surface-container-high": "#e3e9ec",
        "surface-tint": "#4f6073",
        outline: "#737c7f",
        "primary-fixed": "#d2e4fb",
        "on-secondary-container": "#3c5561",
        "on-primary-fixed-variant": "#4c5d70",
        tertiary: "#526262",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#2b3437",
        error: "#9f403d",
        "primary-fixed-dim": "#c4d6ed",
        surface: "#f8f9fa",
        "inverse-on-surface": "#9b9d9e",
        "error-dim": "#4e0309",
        "inverse-primary": "#d5e7fe",
        "inverse-surface": "#0c0f10",
        "primary-container": "#d2e4fb",
        "surface-bright": "#f8f9fa",
        "on-tertiary-container": "#4b5c5b",
        "surface-container": "#eaeff1",
        "on-tertiary-fixed": "#394949",
        "tertiary-container": "#dff1f0",
        "on-secondary": "#f2faff",
        primary: "#4f6073",
        "surface-container-highest": "#dbe4e7",
        "tertiary-fixed-dim": "#d1e3e2",
        "primary-dim": "#435467",
        "on-tertiary": "#eafdfc",
        "secondary-container": "#cbe7f5",
        "surface-container-low": "#f1f4f6",
        "surface-dim": "#d1dce0",
        "tertiary-fixed": "#dff1f0",
        "on-secondary-fixed-variant": "#455f6b",
        "surface-variant": "#dbe4e7",
        "tertiary-dim": "#465656",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      keyframes: {
        "indeterminate-bar": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(300%)" },
        },
      },
      animation: {
        "indeterminate-bar": "indeterminate-bar 1.5s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
